app:
    resource: '@AppBundle/Controller/'
    type: annotation

easy_admin_bundle:
    # resource: "@EasyAdminBundle/Controller/AdminController.php"
    resource: '@AppBundle/Controller/AdminController.php'
    type:     annotation
    prefix:   /

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'

api:
    type:     rest
    resource: '@ApiBundle/Controller/'
    prefix: /api

# api doc
app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc

app_mock:
    resource: '@MockBundle/Controller/'
    type: annotation
    prefix: /mock
