# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        api_key_user_provider:
            id: AppBundle\Security\ApiKeyUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            simple_preauth:
                authenticator: AppBundle\Security\ApiKeyAuthenticator
            provider: api_key_user_provider
            # @see https://symfony.com/doc/current/reference/configuration/security.html#firewall-context
            context: primary_auth
            logout_on_user_change: true

        mock:
            pattern: ^/mock
            security: false

        main:
            pattern: ^/
            http_basic:
                provider: api_key_user_provider
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            # @see https://symfony.com/doc/current/reference/configuration/security.html#firewall-context
            context: primary_auth
            logout_on_user_change: true

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/app, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
